export const editAdressIconAltText = "Edit"
export const ethAdressLabel = "Adress"
export const ethAdressPlaceholderText = "Enter Eth adress"
export const ethBalanceLabel = "Balance"
export const logoText = "FONDU"
export const dollarSymbol = "USD"
export const ethereumSymbol = "Eth"
export const getTestEthButtonText = "Get test ETH to your wallet"
export const realNetworkButtonText = "Real network"
export const testNetworkButtonText = "Test network"
export const erc20contractName = "ERC-20"
export const erc721ContractName = "ERC-721"
export const tokenTypeTabText = "Token type"
export const tokenSettingsTabText = "Token settings"
export const deploymentTabText = "Deployment"
export const previousButtonText = "Previous step"
export const nextButtonText = "Next step"
export const tokenNameLabel = `Human-readable name of your token like "Fondu", "Bitcoin" or "Ethereum"`
export const tokenNamePlaceholderText = "Token name"
export const tokenSymbolLabel = `Symbol of your token like "FDU", "BTC" or "ETH"`
export const tokenSymbolPlaceholderText = "Token symbol"
export const ethWalletLabel = "ETH wallet that will receive the collected funds"
export const ethWalletPlaceholderText = "ETH wallet"
export const numberOfDecimalsLabel = "Number of decimals your currency supports"
export const numberOfDecimalsPlaceholderText = "Number of decimals"
export const tokensPerEthLabel =
  "How many of your tokens will user get for 1 ETH"
export const tokensPerEthPlaceholderText = "Tokens for 1 ETH"
export const crowdsaleTimedCheckboxText = "Crowdsale is bounded by a time frame"
export const cappedTokensCheckboxText =
  "You have the maximum value of tokens sold"
export const cappedTokensLabel =
  "What is the maximum amount of tokens you intend to raise?"
export const cappedTokensPlaceholderText = "Amount of tokens"
export const whitelistCheckboxText =
  "Accept Ethereum only from the whitelisted addresses"
export const checkSettingsText = "Check your settings again:"
export const tokenTypeCheckText = "Token type:"
export const tokenNameCheckText = "Token name:"
export const tokenSymbolCheckText = "Token symbol:"
export const tokensPerEthCheckText = "Tokens for 1 ETH:"
export const recieverCheckText = "Reciever:"
export const decimalsCheckText = "Decimals:"
export const crowdsaleTimedCheckText = "Crowdsale is bounded by a time frame"
export const cappedTokensCheckText = "Amount of tokens intend to raise: "
export const whitelistCheckText =
  "Accept Ethereum only from the whitelisted addresses"
